version: '3.8'
services:
  app:
    build: . # Build from the Dockerfile in the current directory
    ports:
      - '3100:3100' # Map host port 3000 to container port 3000
    environment:
      MONGODB_URI: mongodb://mongo:27017/student_scores # Use mongo service name as hostname
      NODE_ENV: development # Or production for production-like local testing
    depends_on:
      - mongo # App depends on mongo service
    networks:
      - app-network # Attach to the app-network

  mongo:
    image: mongo:latest # Use the latest MongoDB image from Docker Hub
    ports:
      - '27017:27017' # Map host port 27017 to container port 27017
    networks:
      - app-network # Attach to the app-network
    volumes:
      - mongo-data:/data/db # Persist MongoDB data in a named volume

networks:
  app-network: # Define a network for app and mongo to communicate
    driver: bridge

volumes:
  mongo-data: # Define a named volume for MongoDB data persistence
